name: pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: go vet ./...
  
  deploy:
    name: Public app in DockerHub
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login in to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOKCER_USERNAME}}
            password: ${{secrets.DOCKER_ACCESS_TOKEN}}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5.5.1
          with:
            images: paranoia0/final_cicd
    
        - name: Build and push Docker Inage
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}    




    
